# Generated by Django 4.0.4 on 2022-04-24 06:03
#it was done by anushka
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_type',
            new_name='UserType',
        ),
    ]
