# Generated by Django 4.0.4 on 2022-04-24 06:13
# it was done by vedant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_type_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seeker',
            field=models.BooleanField(default=False),
        ),
    ]
