# Generated by Django 4.0.4 on 2022-04-24 06:21
# it was done vedant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_recruiter_user_is_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Name', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
