# Generated by Django 3.2.9 on 2022-04-28 08:43
# 
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_name_delete_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            #in this above model id is treated as primary key
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            #here sub category name is called as Foregin key
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('birthDate', models.DateField()),
                ('current_job_role', models.CharField(max_length=255)),
                ('current_company', models.CharField(max_length=255)),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            # It finds the to enterv the datatypes like char, string,choices.
            # it is for seeker profile
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_phone', models.IntegerField()),
                ('job_role', models.CharField(max_length=255)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=1000)),
                ('organization', models.CharField(max_length=255)),
                ('remuneration', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('skill_required_1', models.CharField(max_length=255)),
                ('skill_required_2', models.CharField(max_length=255)),
                ('skill_required_3', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_required_4', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_required_5', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('job_ad_flag', models.CharField(max_length=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recruiterprofile')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcategory')),
            ],
            # the above methods are  it is used to add the details of job seeker.
        ),
    ]
