# Generated by Django 3.2.9 on 2022-04-28 08:50
# it was done by karthik
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_job_recruiterprofile_seekerprofile_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_ad_flag',
        ),
    ]
