# Generated by Django 3.2.9 on 2022-04-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_job_job_ad_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
