# Generated by Django 4.0.4 on 2022-04-29 13:02
# it was done by vedant
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220428_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='job_role',
        ),
    ]
