# Generated by Django 4.0.4 on 2022-05-01 19:03
# it was done by Maheswari
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_application_subcategory_seekerskillset_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
    ]
